import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectsSidebar: [{type: 'autogenerated', dirName: 'projects'}],
  owaspSidebar: [{type: 'autogenerated', dirName: 'owasp-juice-shop'}],
};

export default sidebars;
